user www-data;
worker_processes auto;
events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout  65;

  map $http_x_forwarded_proto $fcgi_https {
    default off;
    https on;
  }

  map $http_x_forwarded_proto $fcgi_server_port {
    default 80;
    https 443;
  }

  server {
    listen 80;
    server_name _;

    root /var/www/app/public;
    index index.php index.html;

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param HTTPS $fcgi_https;
      fastcgi_param REQUEST_SCHEME $http_x_forwarded_proto;
      fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
      fastcgi_param HTTP_X_FORWARDED_PORT $fcgi_server_port;
      fastcgi_param SERVER_PORT $fcgi_server_port;
      fastcgi_pass 127.0.0.1:9000; # php-fpm
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
      try_files $uri =404;
      access_log off;
      expires 30d;
    }
  }
}
